name: "Test"
description: "Tests a node project"

inputs:
  node-version:
    description: "Node version"
    type: "string"
    required: false
    default: "18.x"

  restore-build:
    description: "Retrieve the build artifact for this commit"
    type: "boolean"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Restore cached dependencies
      id: npm-cache-restore
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json', 'package.json') }}

    - uses: actions/download-artifact@v3
      if: restore-build
      with:
        name: build-${{ github.sha }}

    - run: npm test
      shell: bash
